# Generated by Django 2.2.10 on 2024-05-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_auto_20240521_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('InProgress', 'InProgress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], max_length=20),
        ),
    ]
